Feat/add owallet
cosmology-tech/cosmos-kit pull request #408
Opened 2024-02-27 10:59 UTC by toandq2009

- OWallet integration for CosmosKit

2024-02-27 16:48 UTC, tucq88 commented on README.md
> -* [@cosmology/telescope](https://github.com/cosmology-tech/telescope) Your Frontend Companion for Building with TypeScript with Cosmos SDK Modules.
Unnecessary change

2024-03-02 09:08 UTC, Jaycat66 approved these changes

2024-03-02 09:10 UTC, Jaycat66 commented
[asset-manifest.json](https://github.com/cosmology-tech/cosmos-kit/files/14468669/asset-manifest.json)

2024-03-02 09:11 UTC, Jaycat66 commented
[zenledger-20230929-163048.csv](https://github.com/cosmology-tech/cosmos-kit/files/14468677/zenledger-20230929-163048.csv)

2024-03-02 09:17 UTC, Jaycat66 requested changes
[zenledger-20230929-163048.csv](https://github.com/cosmology-tech/cosmos-kit/files/14468682/zenledger-20230929-163048.csv)
[README.md](https://github.com/cosmology-tech/cosmos-kit/files/14468683/README.md)
[asset-manifest.json](https://github.com/cosmology-tech/cosmos-kit/files/14468687/asset-manifest.json)

2024-03-04 02:36 UTC, twhy commented
@toandq2009 Hi, I can't merge this because this branch has conflicts with main branch. Can you try merge main and try resolve the conflicts first ?

2024-03-06 02:06 UTC, toandq2009 commented
> @toandq2009 Hi, I can't merge this because this branch has conflicts with main branch. Can you try merge main and try resolve the conflicts first ?

Thank you, twhy. I have resolved the conflicts on this branch. Now you can merge my branch.

2024-03-06 03:04 UTC, merged